version: '2'
services:
  wordpress-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
      - ${public_port}:${public_port}
  nginx:
    image: tutum/nginx
    links:
      - php
    volumes:
      - /opt/data/{{ .Stack.Name }}/conf:/etc/nginx/sites-enabled/
      - /opt/data/{{ .Stack.Name }}/logs:/var/log/nginx/
      - /opt/data/{{ .Stack.Name }}/public:/app/
  php:
    build: https://github.com/F3LDS/php7.git
    links:
      - mysql
    volumes:
      - /opt/data/{{ .Stack.Name }}/public:/app/
  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - MYSQL_USER={{ .Stack.Name }}
      - MYSQL_PASSWORD=${mysql_user_password}
      - MYSQL_DATABASE={{ .Stack.Name }}
    volumes:
      - /opt/data/{{ .Stack.Name }}/db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: nazarpc/phpmyadmin
    restart: always
    links:
      - mysql
    environment:
      - "MYSQL_HOST=mysql:3306"
      - "PMA_ABSOLUTE_URI=pma.${DOMAIN}"
#volumes:
#  data:
#    driver: rancher-nfs
#  data/public:
#    driver: rancher-nfs