version: '2'
catalog:
  name: "TyTo Wordpress"
  version: "v1.0"
  description: "Wordpress stack made for TyTo"
  questions:    
    - variable: public_port
      description: "public port to access the wordpress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: mysql_root_password
      label: "Database Root Password"
      required: true
      type: "string"
    - variable: mysql_user_password
      label: "Database User Password"
      required: true
      type: "string"
services:
  wordpress-lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: wordpress
        source_port: ${public_port}
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
  nginx:
    scale: 1
    retain_ip: true
    health_check:
      port: 80
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET / HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
  php:
    scale: 1
    retain_ip: true
  mysql:
    scale: 1
    retain_ip: true
  phpmyadmin:
    scale: 1
    retain_ip: true